Repository Team-Beforeget/Beforeget-iOS, pull requests merged in 2022-01, with the labels that each got.

#11 [Feat] Navigation Design System 추가 (#5)
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/DesignSystem/Font/BDSFont.swift
  Beforeget-iOS/Beforeget-iOS/Global/DesignSystem/UIComponet/BDSNavigationBar.swift
  Beforeget-iOS/Beforeget-iOS/Global/Extension/UILabel+.swift
  Beforeget-iOS/Beforeget-iOS/Global/Extension/UIViewController+.swift
Labels: 코드리뷰멈춰

#12 Feat/6 report
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Extension/UILabel+.swift
  Beforeget-iOS/Beforeget-iOS/Resource/Support/SceneDelegate.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/Components/MonthYearPickerView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/Components/RespondingButton.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportDescriptionView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportRankingView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P0, 도움, 코드리뷰

#13 Feat/8-main
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Models/Media.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Views/Cells/RecordCollectionViewCell.swift
  Beforeget-iOS/Podfile.lock
Labels: 밴, P0, 도움, 코드리뷰

#15 [Fix] xcode 문제 해결 (#8)
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 밴, 도움

#16 Feat/6 report
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Views/RecordCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Podfile.lock
Labels: 쏘, 도움

#17 Feat/10-writing
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Resource/Support/SceneDelegate.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Models/MediaType.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/MediaSelectViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/MediaSelectCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Components/WritingHeaderView.swift
  Beforeget-iOS/Podfile.lock
Labels: 밴, P0, 도움, 코드리뷰

#20 Feat/6-report
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Constant/Assets+Generated.swift
  Beforeget-iOS/Beforeget-iOS/Global/Extension/UIView+.swift
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/box_sentence_empty.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/box_sentence_empty.imageset/box_sentence_empty.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/box_sentence_empty.imageset/box_sentence_empty@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/box_sentence_empty.imageset/box_sentence_empty@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Support/Info.plist
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/BarView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/Cells/ReportSentenceCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportOnePageView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportSentenceView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P0, 도움, 레이아웃, 코드리뷰

#34 Feat/28 report auto layout
  Beforeget-iOS/Beforeget-iOS/Global/DesignSystem/UIComponet/BDSNavigationBar.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/BarView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportDescriptionView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportOnePageView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportRankingView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportSentenceView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P0, 레이아웃, 코드리뷰

#38 Feat/31, 30, 35 - View Flow, MyPage View Layout, Popup View
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Constant/Assets+Generated.swift
  Beforeget-iOS/Beforeget-iOS/Global/DesignSystem/UIComponet/BDSPopupView.swift
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnInfo.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnInfo.imageset/btnInfo.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnInfo.imageset/btnInfo@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnInfo.imageset/btnInfo@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNameEdit.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNameEdit.imageset/btnNameEdit.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNameEdit.imageset/btnNameEdit@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNameEdit.imageset/btnNameEdit@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNext.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNext.imageset/btnNext.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNext.imageset/btnNext@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/btnNext.imageset/btnNext@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnPhoto.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnPhoto.imageset/icnPhoto.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnPhoto.imageset/icnPhoto@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnPhoto.imageset/icnPhoto@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgBack.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgBack.imageset/imgBack.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgBack.imageset/imgBack@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgBack.imageset/imgBack@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgDelete.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgDelete.imageset/imgDelete.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgDelete.imageset/imgDelete@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgDelete.imageset/imgDelete@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgEdit.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgEdit.imageset/imgEdit.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgEdit.imageset/imgEdit@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgEdit.imageset/imgEdit@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgSave.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgSave.imageset/imgSave.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgSave.imageset/imgSave@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/imgSave.imageset/imgSave@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Support/SceneDelegate.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Complete/Controllers/CompleteViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Controllers/DetailRecordDeletePopupViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Controllers/DetailRecordEditPopupViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Controllers/DetailRecordViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Components/DeletePopupView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Components/EditPopupView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/MyRecord/Controllers/MyRecordViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/MediaSelectViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostBackPopupViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostSavePopupViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Components/WritingBackPopupView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Components/WritingSavePopupView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Setting/Controllers/SettingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Setting/Views/Cells/SettingTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Setting/Views/Components/SettingFooterView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Setting/Views/Components/SettingHeaderView.swift
Labels: 루, P0, 도움, 레이아웃, 기능, 코드리뷰

#37 Feat/33 review modal
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/OneLineViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/BadOneLineCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/GoodOneLineCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/OneLineTextCollectionViewCell.swift
Labels: 쏘, P1, 레이아웃, 기능, 코드리뷰

#40 Feat/32 auto layout
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/MediaSelectCollectionViewCell.swift
Labels: 쏘, P0, 레이아웃, 코드리뷰

#39 Feat/10 writing
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Constant/Assets+Generated.swift
  Beforeget-iOS/Beforeget-iOS/Global/Constant/NotificationName.swift
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckActive.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckActive.imageset/icnCheckActive.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckActive.imageset/icnCheckActive@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckActive.imageset/icnCheckActive@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckInactive.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnCheckInactive.imageset/icnCheckInactive@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/img_example.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/img_example.imageset/img_example.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/img_example.imageset/img_example@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/img_example.imageset/img_example@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Support/SceneDelegate.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/AddItemViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/AddItemCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/CommentTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/OneLineReviewTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/TitleTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Components/WritingHeaderView.swift
  Beforeget-iOS/Podfile.lock
Labels: 밴, P0, 도움, 기능, 코드리뷰

#47 통계뷰 서버 연결
  .gitignore
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/MainModel/Main.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/ReportModel/FirstReport.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/ReportModel/FourthReport.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/ReportModel/SecondReport.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/ReportModel/ThirdReport.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/ReportModel/TotalReport.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/ReportAPI/ReportAPI.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/ReportAPI/ReportService.swift
  Beforeget-iOS/Beforeget-iOS/Network/Base/BaseResponse.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/OneLineTextCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/BarView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/Components/MonthYearPickerView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportDescriptionView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportOnePageView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportSentenceView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P0, 도움, 서버통신, 코드리뷰

#51 Feat/10 writing
  Beforeget-iOS/Beforeget-iOS/Global/Constant/NotificationName.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/OneLineViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/BadOneLineCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/GoodOneLineCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/OneLineReviewTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/OneLineTextCollectionViewCell.swift
  Beforeget-iOS/Podfile.lock
Labels: 밴, P0, 도움, 기능, 코드리뷰

#53 Feat/43 report network
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Constant/Assets+Generated.swift
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainBook.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainBook.imageset/icnBook.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainBook.imageset/icnBook@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainBook.imageset/icnBook@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMovie.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMovie.imageset/icnMovie.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMovie.imageset/icnMovie@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMovie.imageset/icnMovie@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMusic.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMusic.imageset/icnMusic.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMusic.imageset/icnMusic@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainMusic.imageset/icnMusic@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainTv.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainTv.imageset/icnTv.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainTv.imageset/icnTv@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainTv.imageset/icnTv@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainWebtoon.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainWebtoon.imageset/icnWebtoon.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainWebtoon.imageset/icnWebtoon@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainWebtoon.imageset/icnWebtoon@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainYoutube.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainYoutube.imageset/icnYoutube.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainYoutube.imageset/icnYoutube@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMainYoutube.imageset/icnYoutube@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectBook.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectBook.imageset/icnMediaSelectBook.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectBook.imageset/icnMediaSelectBook@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectBook.imageset/icnMediaSelectBook@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMovie.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMovie.imageset/icnMediaSelectMovie.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMovie.imageset/icnMediaSelectMovie@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMovie.imageset/icnMediaSelectMovie@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMusic.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMusic.imageset/icnMediaSelectMusic.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMusic.imageset/icnMediaSelectMusic@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectMusic.imageset/icnMediaSelectMusic@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectTv.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectTv.imageset/icnMediaSelectTv.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectTv.imageset/icnMediaSelectTv@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectTv.imageset/icnMediaSelectTv@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectWebtoon.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectWebtoon.imageset/icnMediaSelectWebtoon.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectWebtoon.imageset/icnMediaSelectWebtoon@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectWebtoon.imageset/icnMediaSelectWebtoon@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectYoutube.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectYoutube.imageset/icnMediaSelectYoutube.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectYoutube.imageset/icnMediaSelectYoutube@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Assets.xcassets/icnMediaSelectYoutube.imageset/icnMediaSelectYoutube@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Colors.xcassets/icnPhoto.imageset/Contents.json
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Colors.xcassets/icnPhoto.imageset/icnPhoto.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Colors.xcassets/icnPhoto.imageset/icnPhoto@2x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/Colors.xcassets/icnPhoto.imageset/icnPhoto@3x.png
  Beforeget-iOS/Beforeget-iOS/Resource/Asset/threeWhiteLine.json
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Views/RecordCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Select/MediaSelectCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportLoadingView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportSentenceView.swift
Labels: 쏘, P0, 코드리뷰

#55 Feat/36-writing network
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/PostModel/OneLine.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/PostModel/PostRequest.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/PostModel/PostResponse.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/PostModel/RecommendItem.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/PostAPI/PostAPI.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/PostAPI/PostService.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Filter/Views/Cells/DateTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Models/MediaType.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/AddItemViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/OneLineViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Controllers/PostViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/GoodOneLineCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/TitleTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Cells/Write/WriteTextTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Post/Views/Components/WritingHeaderView.swift
Labels: 밴, P0, 도움, 서버통신, 코드리뷰

#56 통계뷰 레이아웃 수정 및 month 버튼 구현
  Beforeget-iOS/Beforeget-iOS/Global/Extension/UIView+.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/ReportAPI/ReportAPI.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/Components/MonthYearPickerView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportOnePageView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportSentenceView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P1

#58 Feat/45 record network
  Beforeget-iOS/Beforeget-iOS.xcodeproj/project.pbxproj
  Beforeget-iOS/Beforeget-iOS/Global/Extension/String+.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/MainModel/Main.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/MyRecordModel/MyDetailRecord.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIModel/MyRecordModel/MyRecord.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/MainAPI/MainAPI.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/MainAPI/MainService.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/MyRecordAPI/MyRecordAPI.swift
  Beforeget-iOS/Beforeget-iOS/Network/APIService/MyRecordAPI/MyRecordService.swift
  Beforeget-iOS/Beforeget-iOS/Network/Base/MoyaLoggerPlugin.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Complete/Controllers/CompleteViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Controllers/DetailRecordViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/CommaTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/CommentDetailTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/GenreCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/GenreTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/ImageTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/LineTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/LinkTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/ReviewTagCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/SongListTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/SongTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/StampCollectionViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/StampTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Cells/TextTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/DetailRecord/Views/Components/DetailRecordHeaderView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Filter/Controllers/FilterModalViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Controllers/MainViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Main/Models/MediaType.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/MyRecord/Controllers/MyRecordViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/MyRecord/Models/Record.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/MyRecord/Views/Cells/MyRecordEmptyTableViewCell.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/MyRecord/Views/Cells/MyRecordTableViewCell.swift
Labels: 루, 도움, 코드리뷰

#62 [Hotfix] 통계뷰 날짜 선택 버튼 수정 (#54)
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportGraphViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportLabelViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportOnePageViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportRankingViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportSentenceViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Controllers/ReportViewController.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportGraphView.swift
  Beforeget-iOS/Beforeget-iOS/Source/Screen/Report/Views/ReportTopView.swift
Labels: 쏘, P0, 레이아웃
